import { Hono } from 'hono';
import type { Context } from 'hono';
import { requireNip98AuthResolved } from '../auth';
import { buildFlightDeckPgIdentity, resolveFlightDeckPgRequestContext } from '../services/flightdeck-pg-api';
import {
  WAPP_MANAGEMENT_PERMISSION, WAPP_MANAGEMENT_ROLE, WappManagementError,
  claimInstallIntent, completeInstallIntent, createInstallIntent, createWappDelegation,
  evaluateWappManagement, failInstallIntent, getInstallIntent, getWappDelegation,
  getAutopilotInstallIntent, issueInstallIntentClaimChallenge, listAutopilotInstallIntents,
  listInstallIntents, listWappDelegations, normalizeInstallIntent, revokeWappDelegation,
  getManagedWappInstallation, listManagedWappInstallations, requestWappReconciliation, revokeManagedWappInstallation,
} from '../services/wapp-management';
import { getDb } from '../db';

export const wappManagementRouter = new Hono();
type RequestContext = Awaited<ReturnType<typeof resolveFlightDeckPgRequestContext>> & { workspace: NonNullable<Awaited<ReturnType<typeof resolveFlightDeckPgRequestContext>>['workspace']>; actor: NonNullable<Awaited<ReturnType<typeof resolveFlightDeckPgRequestContext>>['actor']>; membership: NonNullable<Awaited<ReturnType<typeof resolveFlightDeckPgRequestContext>>['membership']> };
function error(c: Context, e: unknown, identity?: unknown) { if (e instanceof WappManagementError) return c.json({ error: e.message, code: e.code, status: e.status, identity, details: e.details }, e.status as any); console.error('WApp management route failed', e); return c.json({ error: 'Internal WApp management error', code: 'internal_error', status: 500, identity }, 500); }
async function context(c: Context) {
  const auth = await requireNip98AuthResolved(c); if (auth instanceof Response) return auth;
  const ctx = await resolveFlightDeckPgRequestContext({ workspaceId: c.req.param('workspaceId') || '', actorNpub: auth.userNpub });
  const identity = buildFlightDeckPgIdentity(ctx.workspace, ctx.workspace?.app_npub ?? '');
  if (!ctx.workspace) return c.json({ error: 'Workspace not found', code: 'workspace_not_found', status: 404, identity }, 404);
  if (!ctx.actor || !ctx.membership) return c.json({ error: 'Workspace membership required', code: 'workspace_membership_required', status: 403, identity }, 403);
  const [owner] = await getDb()<any[]>`SELECT a.* FROM flightdeck_pg_actors a JOIN flightdeck_pg_workspace_memberships m ON m.actor_id=a.id AND m.workspace_id=${ctx.workspace.id} WHERE a.npub=${ctx.workspace.workspace_owner_npub}`;
  if (!owner) return c.json({ error: 'Workspace owner actor not found', code: 'workspace_owner_not_found', status: 409, identity }, 409);
  return { auth, context: ctx as RequestContext, owner, identity };
}
const auditShape = (r: any, operation: string) => ({ operation, permission: WAPP_MANAGEMENT_PERMISSION, role: WAPP_MANAGEMENT_ROLE, owner_actor_id: r.owner?.id ?? r.owner_actor_id, actor_id: r.context?.actor.id, signer_npub: r.auth?.signerNpub, delegation_id: r.delegation?.id ?? null });

wappManagementRouter.post('/workspaces/:workspaceId/wapp-delegations', async (c) => { const r=await context(c); if(r instanceof Response)return r; if(r.context.actor.id!==r.owner.id)return error(c,new WappManagementError('delegation_required','Only the workspace owner may grant wapp_management',403),r.identity); try { const b=await c.req.json(); const delegation=await createWappDelegation({workspaceId:r.context.workspace.id,ownerActorId:r.owner.id,delegateActorId:String(b.delegate_actor_id||''),expiresAt:String(b.expires_at||''),filters:b.filters,ownerSignature:typeof b.owner_signature==='string'?b.owner_signature:null}); return c.json({identity:r.identity,delegation,audit:auditShape(r,'delegation.create')},201); } catch(e){return error(c,e,r.identity);} });
wappManagementRouter.get('/workspaces/:workspaceId/wapp-delegations', async(c)=>{const r=await context(c);if(r instanceof Response)return r;try{return c.json({identity:r.identity,permission:WAPP_MANAGEMENT_PERMISSION,role:WAPP_MANAGEMENT_ROLE,delegations:await listWappDelegations(r.context.workspace.id,r.context.actor.id,r.context.actor.id===r.owner.id)});}catch(e){return error(c,e,r.identity);}});
wappManagementRouter.get('/workspaces/:workspaceId/wapp-delegations/:delegationId', async(c)=>{const r=await context(c);if(r instanceof Response)return r;try{const delegation=await getWappDelegation(r.context.workspace.id,c.req.param('delegationId'),r.context.actor.id,r.context.actor.id===r.owner.id);if(!delegation)throw new WappManagementError('delegation_not_found','Delegation not found',404);return c.json({identity:r.identity,delegation});}catch(e){return error(c,e,r.identity);}});
wappManagementRouter.post('/workspaces/:workspaceId/wapp-delegations/:delegationId/revoke',async(c)=>{const r=await context(c);if(r instanceof Response)return r;if(r.context.actor.id!==r.owner.id)return error(c,new WappManagementError('delegation_required','Only the workspace owner may revoke wapp_management',403),r.identity);try{const delegation=await revokeWappDelegation(r.context.workspace.id,c.req.param('delegationId'),r.context.actor.id);if(!delegation)throw new WappManagementError('delegation_not_found','Delegation not found',404);return c.json({identity:r.identity,delegation,audit:auditShape(r,'delegation.revoke')});}catch(e){return error(c,e,r.identity);}});

wappManagementRouter.post('/workspaces/:workspaceId/wapp-install-intents',async(c)=>{const r=await context(c);if(r instanceof Response)return r;try{const b=await c.req.json();const request=normalizeInstallIntent(b);const authz=await evaluateWappManagement({workspaceId:r.context.workspace.id,actorId:r.context.actor.id,ownerActorId:r.owner.id,request,delegationId:text(b.delegation_id)||null});const payload=await createInstallIntent({workspaceId:r.context.workspace.id,ownerActorId:r.owner.id,actorId:r.context.actor.id,signerNpub:r.auth.signerNpub,delegationId:authz.delegation?.id??null,request});return c.json({identity:r.identity,...payload,audit:{...auditShape({...r,delegation:authz.delegation},'intent.create'),intent_id:payload.intent.id}},payload.replayed?200:201);}catch(e){return error(c,e,r.identity);}});
wappManagementRouter.get('/workspaces/:workspaceId/wapp-install-intents',async(c)=>{const r=await context(c);if(r instanceof Response)return r;try{return c.json({identity:r.identity,intents:await listInstallIntents(r.context.workspace.id,r.context.actor.id,r.context.actor.id===r.owner.id)});}catch(e){return error(c,e,r.identity);}});
wappManagementRouter.get('/workspaces/:workspaceId/wapp-install-intents/:intentId',async(c)=>{const r=await context(c);if(r instanceof Response)return r;try{const intent=await getInstallIntent(r.context.workspace.id,c.req.param('intentId'),r.context.actor.id,r.context.actor.id===r.owner.id);if(!intent)throw new WappManagementError('intent_not_found','Install intent not found',404);return c.json({identity:r.identity,intent});}catch(e){return error(c,e,r.identity);}});

wappManagementRouter.get('/workspaces/:workspaceId/autopilot-wapp-install-intents',async(c)=>{const auth=await requireNip98AuthResolved(c);if(auth instanceof Response)return auth;try{return c.json({intents:await listAutopilotInstallIntents(c.req.param('workspaceId'),auth.signerNpub)});}catch(e){return error(c,e);}});
wappManagementRouter.get('/workspaces/:workspaceId/autopilot-wapp-install-intents/:intentId',async(c)=>{const auth=await requireNip98AuthResolved(c);if(auth instanceof Response)return auth;try{const intent=await getAutopilotInstallIntent(c.req.param('workspaceId'),c.req.param('intentId'),auth.signerNpub);if(!intent)throw new WappManagementError('intent_not_found','Install intent not found for this Autopilot identity',404);return c.json({intent});}catch(e){return error(c,e);}});
wappManagementRouter.post('/workspaces/:workspaceId/autopilot-wapp-install-intents/:intentId/challenge',async(c)=>{const auth=await requireNip98AuthResolved(c);if(auth instanceof Response)return auth;try{const b=await c.req.json();return c.json(await issueInstallIntentClaimChallenge(c.req.param('workspaceId'),c.req.param('intentId'),auth.signerNpub,Number(b.intent_version)));}catch(e){return error(c,e);}});

// Claim/complete/fail authenticate the Autopilot service directly. They do not
// require workspace membership; the immutable owner/delegate chain is on intent.
wappManagementRouter.post('/workspaces/:workspaceId/wapp-install-intents/:intentId/claim',async(c)=>{const auth=await requireNip98AuthResolved(c);if(auth instanceof Response)return auth;try{const b=await c.req.json();const intent=await claimInstallIntent({workspaceId:c.req.param('workspaceId'),id:c.req.param('intentId'),signerNpub:auth.signerNpub,challenge:String(b.challenge||''),intentVersion:Number(b.intent_version),observed:{wapp_installation_id:b.wapp_installation_id,app_id:b.app_id,app_version:b.app_version,publisher_npub:b.publisher_npub,launch_url:b.launch_url,attestation_hash:b.attestation_hash}});return c.json({intent,audit:{operation:'intent.claim',signer_npub:auth.signerNpub}});}catch(e){return error(c,e);}});
wappManagementRouter.post('/workspaces/:workspaceId/wapp-install-intents/:intentId/complete',async(c)=>{const auth=await requireNip98AuthResolved(c);if(auth instanceof Response)return auth;try{const b=await c.req.json();const payload=await completeInstallIntent({workspaceId:c.req.param('workspaceId'),id:c.req.param('intentId'),signerNpub:auth.signerNpub,intentVersion:Number(b.intent_version),observed:b});return c.json({...payload,audit:{operation:'intent.complete',signer_npub:auth.signerNpub}});}catch(e){return error(c,e);}});
wappManagementRouter.post('/workspaces/:workspaceId/wapp-install-intents/:intentId/fail',async(c)=>{const auth=await requireNip98AuthResolved(c);if(auth instanceof Response)return auth;try{const b=await c.req.json();return c.json({intent:await failInstallIntent(c.req.param('workspaceId'),c.req.param('intentId'),auth.signerNpub,String(b.code||''),String(b.message||''),b.observed),audit:{operation:'intent.fail',signer_npub:auth.signerNpub}});}catch(e){return error(c,e);}});

wappManagementRouter.get('/workspaces/:workspaceId/wapp-installations',async(c)=>{const r=await context(c);if(r instanceof Response)return r;try{await evaluateWappManagement({workspaceId:r.context.workspace.id,actorId:r.context.actor.id,ownerActorId:r.owner.id});return c.json({identity:r.identity,installations:await listManagedWappInstallations(r.context.workspace.id)});}catch(e){return error(c,e,r.identity);}});
wappManagementRouter.get('/workspaces/:workspaceId/wapp-installations/:installationId',async(c)=>{const r=await context(c);if(r instanceof Response)return r;try{await evaluateWappManagement({workspaceId:r.context.workspace.id,actorId:r.context.actor.id,ownerActorId:r.owner.id,request:{wapp_installation_id:c.req.param('installationId')}});const installation=await getManagedWappInstallation(r.context.workspace.id,c.req.param('installationId'));if(!installation)throw new WappManagementError('installation_not_found','Installation not found',404);return c.json({identity:r.identity,installation});}catch(e){return error(c,e,r.identity);}});
wappManagementRouter.post('/workspaces/:workspaceId/wapp-installations/:installationId/reconcile',async(c)=>{const r=await context(c);if(r instanceof Response)return r;try{const authz=await evaluateWappManagement({workspaceId:r.context.workspace.id,actorId:r.context.actor.id,ownerActorId:r.owner.id,request:{wapp_installation_id:c.req.param('installationId')}});return c.json({identity:r.identity,installation:await requestWappReconciliation(r.context.workspace.id,c.req.param('installationId'),r.context.actor.id),audit:auditShape({...r,delegation:authz.delegation},'installation.reconcile')},202);}catch(e){return error(c,e,r.identity);}});
wappManagementRouter.post('/workspaces/:workspaceId/wapp-installations/:installationId/revoke',async(c)=>{const r=await context(c);if(r instanceof Response)return r;try{const authz=await evaluateWappManagement({workspaceId:r.context.workspace.id,actorId:r.context.actor.id,ownerActorId:r.owner.id,request:{wapp_installation_id:c.req.param('installationId')}});return c.json({identity:r.identity,installation:await revokeManagedWappInstallation(r.context.workspace.id,c.req.param('installationId'),r.context.actor.id),audit:auditShape({...r,delegation:authz.delegation},'installation.revoke')});}catch(e){return error(c,e,r.identity);}});
wappManagementRouter.post('/workspaces/:workspaceId/wapp-installations/:installationId/uninstall',async(c)=>{const r=await context(c);if(r instanceof Response)return r;return error(c,new WappManagementError('step_up_required','Uninstall requires owner step-up and Autopilot teardown confirmation',403),r.identity);});

const text=(v:unknown)=>String(v??'').trim();
