/** Served at the stock repository collaboration URL. No provider token or cookie authorizes sharing. */
export function sharingPage(owner: string, repository: string) {
  // Callers accept only canonical slug characters; retain escaping as defense in depth.
  const escape = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
  const endpoint = `/api/v4/git/forgejo/sharing/${encodeURIComponent(owner)}/${encodeURIComponent(repository)}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collaborators · ${escape(owner)}/${escape(repository)}</title>
<style>:root{color-scheme:dark}body{margin:0;background:#171e27;color:#d6e2ee;font:16px/1.5 system-ui}header,main{max-width:1000px;margin:auto;padding:24px}header{border-bottom:1px solid #405063}a{color:#9acfff}section{background:#202c39;border:1px solid #405063;padding:20px;margin:20px 0;border-radius:6px}button,select{padding:10px;margin:4px;border-radius:4px;font:inherit}button{cursor:pointer;background:#fa9139;color:#171e27;border:0}button:disabled{opacity:.5}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid #405063}#status{white-space:pre-wrap}small{display:block;color:#b6c4d3}</style></head><body>
<header><a href="/${escape(owner)}/${escape(repository)}">${escape(owner)} / ${escape(repository)}</a> · Settings · Collaborators</header>
<main><h1>Repository access</h1><p>Share with workspace collaborators or groups. Sign with the Nostr identity that administers this repository.</p><button id="connect">Load sharing with Nostr</button><p id="status" role="status"></p>
<div id="sharing" hidden><section><h2>Collaborators and groups</h2><table><thead><tr><th>Name</th><th>Direct access</th><th>Change access</th></tr></thead><tbody id="rows"></tbody></table><small>Removing a direct grant preserves access inherited from other groups. Group changes apply to their current and future members.</small></section>
<section><h2>Add collaborator or group</h2><select id="principal" aria-label="Collaborator or group"></select><select id="access" aria-label="Access"><option value="read">Read</option><option value="write">Write</option><option value="admin">Administrator</option></select><button id="add">Save access</button></section>
<p>Write permits fetch and work/feature branch pushes and creation. Protected branches retain their repository rules.</p><p>The Forgejo Owners and tower-members teams manage organization membership. Repository sharing uses the collaborators and Tower groups listed here.</p></div></main>
<script>
const endpoint=${JSON.stringify(endpoint)},status=document.querySelector('#status'),connect=document.querySelector('#connect');let state,busy=false;
const hex=b=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('');
async function request(method,body){if(!window.nostr?.signEvent)throw Error('A Nostr browser signer is required.');const url=location.origin+endpoint,raw=body===undefined?undefined:JSON.stringify(body),tags=[['u',url],['method',method],['nonce',crypto.randomUUID()]];if(raw)tags.push(['payload',hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)))]);const event=await window.nostr.signEvent({kind:27235,created_at:Math.floor(Date.now()/1000),content:'',tags});const response=await fetch(url,{method,headers:{authorization:'Nostr '+btoa(JSON.stringify(event)),'content-type':'application/json'},body:raw});const result=await response.json();if(!response.ok)throw Error(result.error+' ('+result.code+')');return result;}
function accessOf(grants){return grants.some(g=>g.permission==='git.repo.admin')?'admin':grants.some(g=>g.permission==='git.repo.write')?'write':grants.some(g=>g.permission==='git.repo.read')?'read':grants.length?'custom':'none';}
function render(){document.querySelector('#sharing').hidden=false;const rows=document.querySelector('#rows'),select=document.querySelector('#principal');rows.replaceChildren();select.replaceChildren();for(const p of state.principals){const name=p.label+(p.principal_type==='group'?' (group)':'');const option=document.createElement('option');option.value=p.principal_id;option.textContent=name;select.append(option);const grants=state.grants.filter(g=>g.principal_type===p.principal_type&&(g.principal_actor_id||g.principal_group_id)===p.principal_id);if(!grants.length)continue;const tr=document.createElement('tr'),label=document.createElement('td'),access=document.createElement('td'),actions=document.createElement('td');label.textContent=name;access.textContent=accessOf(grants);for(const value of ['read','write','admin','none']){const b=document.createElement('button');b.textContent=value==='none'?'Remove':value==='admin'?'Administrator':value;b.onclick=()=>change(p,value);actions.append(b);}tr.append(label,access,actions);rows.append(tr);}status.textContent=state.ready?'Sharing is applied.':'Sharing is saved in Tower. Forgejo reconciliation is pending; reload to check.';}
async function run(action){if(busy)return;busy=true;try{await action();}catch(error){status.textContent=error.message;}finally{busy=false;}}
async function load(){state=await request('GET');render();}
async function change(p,access){await run(async()=>{status.textContent='Sign to save '+access+' access for '+p.label+'.';await request('POST',{expected_policy_revision:state.policy_revision,principal_type:p.principal_type,principal_id:p.principal_id,...(p.forgejo_user_id?{forgejo_user_id:p.forgejo_user_id}:{}),access});await load();});}
connect.onclick=()=>run(load);document.querySelector('#add').onclick=()=>{const p=state.principals.find(p=>p.principal_id===document.querySelector('#principal').value);if(p)change(p,document.querySelector('#access').value);};
</script></body></html>`;
}
